language: node_js
stages:
  - build
  - quality

cache:
  paths:
    - node_modules/

build:
  stage: build
  script:
    - yarn install

linting:
  stage: quality
  script:
    - yarn run eslint .
    - yarn run eslint --fix
